Fail on dead processes (#47)
* Fail on dead processes

Same bug as https://github.com/elifesciences/search/pull/108

* Fail fast on problems in the creation of the database

diff --git a/bin/wait-for-empty-queue b/bin/wait-for-empty-queue
--- a/bin/wait-for-empty-queue
+++ b/bin/wait-for-empty-queue
@@ -11,14 +11,17 @@ while true; do
     # `|| true` avoid failing the script when there are no results
     watches=$(pgrep -cf queue:watch || true)
     if [ "$watches" -eq "0" ]; then
-        echo "No alive queue:watch processes, failing"
+        echo "No alive queue:watch processes"
         break
     fi
     sqs_queue=$(bin/console --env=$environment queue:count)
     echo "Job in SQS queue (approximate): $sqs_queue"
     if [ "$sqs_queue" -eq 0 ]; then
         echo "No more SQS messages, finished waiting"
-        break
+        exit 0
     fi
     sleep 1
 done
+
+echo "Failing"
+exit 2
